# api redirect
[[redirects]]
  from = "/api/*"
  to = "https://rymostore.onrender.com/api/:splat"
  status = 200
  force = true
# SPA router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200